### ISSUE TITLE
Suppression the user warnings that providing better report readability 

### ISSUE THREAD

**Issue by waiming** [UBC-MDS/Online-Shoppers-Purchasing-Intention-Prediction#18]
the user warning sin cell running Random search of hyperparameterer are repeating and known issues. These could be suppressed so that making report with better readability.

`categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [4] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
[/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:242](http://localhost:8888/Users/wmwong/miniforge3/envs/online-shopping-prediction/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py#line=241): UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(`

**Comment by Stephanie-Ta** [comment]
Great suggestion!

**Comment by waiming** [comment]
I think we can make the suppression after all coding and analysis set, so that we won't suppress any other warnings  during the development steps. 

Here is the reference code snippet for the suppression:
`import warnings
warnings.filterwarnings("ignore", category=UserWarning, module='sklearn')`
