### ISSUE TITLE
no anomalous correlations between features/explanatory variables

### ISSUE THREAD

**Issue by jdaduica** [UBC-MDS/Online-Shoppers-Purchasing-Intention-Prediction#55]

**Comment by jdaduica** [comment]
I am doing the feature-feature correlations and it seems that the features administrative-administrative_duration, informational- informational_duration, and productrelated- productrelated_duration all have high correlation. I think this makes sense to me because the number of pages someone visits would be higher with duration so this could be the reason for the correlation. I looked at the weights and the features without duration have lower weights so I am going to remove these features. Is everyone okay with this? Let me know

**Comment by Stephanie-Ta** [comment]
That is ok with me! I agree with your rationale/reasoning

**Comment by waiming** [comment]
That makes sense!
